[build]
  publish = "."

# Global headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=()"
    # Performance optimizations
    Vary = "Accept-Encoding"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "same-origin"

# HTML compression and caching
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    
# Critical CSS files
[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

# Cache headers for static assets
[[headers]]
  for = "/**/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Blog content cache
[[headers]]
  for = "/blog/*.html"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/blog.html"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# SEO files cache
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# SEO-friendly redirects
[[redirects]]
  from = "/bpdb-calculator"
  to = "/index.html?provider=bpdb"
  status = 200

[[redirects]]
  from = "/desco-calculator"
  to = "/index.html?provider=desco"
  status = 200

[[redirects]]
  from = "/dpdc-calculator"
  to = "/index.html?provider=dpdc"
  status = 200

[[redirects]]
  from = "/wzpdcl-calculator"
  to = "/index.html?provider=wzpdcl"
  status = 200

[[redirects]]
  from = "/bangladesh-electricity-rates-2025"
  to = "/index.html?page=rates"
  status = 200

[[redirects]]
  from = "/energy-saving-tips-bangladesh"
  to = "/energy-tips.html"
  status = 301

[[redirects]]
  from = "/appliance-power-consumption-bangladesh"
  to = "/index.html?page=appliances"
  status = 200

# Redirect old URLs to new structure
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy.html"
  status = 301

[[redirects]]
  from = "/terms-of-service"
  to = "/terms.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

[[redirects]]
  from = "/energy-tips"
  to = "/energy-tips.html"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 301

# Fallback for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://bdbillcalculator.netlify.app/*"
  to = "https://bdbillcalculator.netlify.app/:splat"
  status = 301
  force = true

# Plugin configurations for optimization
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.45
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://bdbillcalculator.netlify.app"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing"
    ]
